### ISSUE TITLE
Travis PR and on change builds

### ISSUE THREAD

**Issue by ryanplusplus** [lua-lake/lake#4]

**Comment by cbeeler** [comment]
Install process was:

```
- curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
- curl -L http://git.io/lenv | perl
- source ~/.lenvrc
- lenv install-lj 2.0.4
- lenv use-lj 2.0.4
- luarocks install busted
- lit install
```

`lenv` might not be needed on Travis, `luajit` and `luarocks` are on `apt-get`, but this more closely matches the developer setup.

**Comment by ryanplusplus** [comment]
Getting via `lenv` is the right way to go. If you get from `apt-get` you're going to get a `luarocks` that isn't run on `luajit` or even `lua` 5.1.

**Comment by cbeeler** [comment]
Done!
